name: GitHub to pub sub action
on: [push]
jobs:
  Explore-Actions:
    runs-on: ubuntu-latest
    env:
        GOOGLE_APPLICATION_CREDENTIALS: key.json
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |
          gcloud config set project test-cloud-day
          echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud pubsub topics publish projects/test-cloud-day/topics/test --message="hello"
