name: GitHub to pub sub action
on: [push]
jobs:
  Pipeline-trigger-actions:
    runs-on: ubuntu-latest
    env:
        GOOGLE_APPLICATION_CREDENTIALS: key.json
    steps:
      - uses: google-github-actions/setup-gcloud@master
      - run: |
          gcloud config set project test-cloud-day
          echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud pubsub topics publish projects/test-cloud-day/topics/test --message="ewogICJwaXBlbGluZV9zcGVjX3VyaSI6ICJnczovL3BpcGVsaW5lcy1iNDUzNi9oZWxsb193b3JsZF9zY2hlZHVsZWRfcGlwZWxpbmUuanNvbiIsCiAgInBhcmFtZXRlcl92YWx1ZXMiOiB7fQp9Cg=="
