name: GitHub to pub sub action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authorize
        run: gcloud auth
      - name: Use gcloud CLI
        run: gcloud pubsub topics publish projects/test-cloud-day/topics/test --message="hello"
