name: GitHub to pub sub action
on: [push]
env:
    GOOGLE_APPLICATION_CREDENTIALS: key.json
jobs:
  Explore-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud config set project $project_id
      - run: gcloud pubsub topics publish projects/test-cloud-day/topics/test --message="hello"
