name: GitHub Actions Demo
on: [push]
env:
  TEST_VAR: mYBAR
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by a ${{ TEST_VAR }} event."
